import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.bold]
family = "Mononoki Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Mononoki Nerd Font"
style = "SemiBold"

[font.italic]
family = "Mononoki Nerd Font"
style = "Light"

[font.normal]
family = "Mononoki Nerd Font"
style = "Regular"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.95
blur = true
startup_mode = "Maximized"
dynamic_title = true

[window.padding]
x = 23
y = 20

